name: CI
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Build the deployment
      run: npm run build
    - name: Push the deployment to the gh pages branch
      run: npm run deploy